# Generated by Django 4.0.4 on 2022-06-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineHomeServiceApp', '0004_alter_worker_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=50)),
                ('home_address', models.CharField(max_length=250)),
                ('pincode', models.IntegerField()),
                ('date', models.DateField()),
                ('Time', models.TimeField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
