# Generated by Django 4.0.4 on 2022-06-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineHomeServiceApp', '0005_bookservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookService',
        ),
    ]
