# Generated by Django 4.0.4 on 2022-06-19 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineHomeServiceApp', '0006_delete_bookservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineHomeServiceApp.worker')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineHomeServiceApp.appointmentschedule')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointmentbooking', to='OnlineHomeServiceApp.customer')),
            ],
        ),
    ]
