# Generated by Django 4.0.4 on 2022-06-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineHomeServiceApp', '0007_appointmentschedule_appointmentbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbooking',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='OnlineHomeServiceApp.customer'),
        ),
    ]
