# Generated by Django 4.0.4 on 2022-07-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineHomeServiceApp', '0010_creditcard_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
