# Generated by Django 4.0.4 on 2022-07-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineHomeServiceApp', '0012_alter_creditcard_card_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
