# Generated by Django 4.0.4 on 2022-07-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineHomeServiceApp', '0014_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='user_id',
        ),
    ]
