# Generated by Django 4.0.4 on 2022-07-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineHomeServiceApp', '0015_rename_user_feedback_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_id',
        ),
    ]
