# Generated by Django 4.0.4 on 2022-07-15 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineHomeServiceApp', '0016_remove_feedback_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineHomeServiceApp.customer'),
        ),
    ]
